version: 2.1
orbs:
  cypress: cypress-io/cypress@3.1.3
executor: cypress/default

workflows:
  build:
    jobs:
      # run on 2 machines using Chrome browser
      - cypress/run:
          name: "testrun"
          package-manager: yarn
          install-browsers: true
          cypress-command: "yarn e2e:record:parallel --browser chrome --record --key 3707ee86-a1d2-451e-804d-d1c8c2e68903 --parallel --group 2x-chrome on CircleCI"
          parallelism: 2
          post-steps:
            - store_test_results:
                path: cypress/reports/mocha
