version: 2.1
orbs:
  cypress: cypress-io/cypress@3.1.3

executors:
  mac:
    macos:
      # Executor should have Node >= required version
      xcode: "14.0.0"

  browsers:
    docker:
      - image: "cypress/browsers:node-18.15.0-chrome-111.0.5563.146-1-ff-111.0.1-edge-111.0.1661.62-1"

jobs:
  mac-test:
    executor: mac
    steps:
      - cypress/install:
          post-install: "npm run build"
      # show Cypress cache folder and binary versions
      # to check if we are caching previous binary versions
      - run: npx cypress cache path
      - run: npx cypress cache list
      - run: npx cypress info
      - cypress/run-tests:
          start-command: "npm run start"
          cypress-command: "npx cypress run --record --group Mac build"

  release:
    executor: cypress/default
    steps:
      - checkout
      - run: npx semantic-release@19.0.3

workflows:
  mac-build:
    jobs:
      - mac-test

  linux-build:
    jobs:
      # run on 2 machines using Chrome browser
      - cypress/run:
          name: "2 machines using Chrome"
          start-command: "npm run start"
          install-browsers: true
          cypress-command: "npx cypress run --browser chrome --record --parallel --group 2x-chrome on CircleCI"
          parallelism: 2
          post-steps:
            # show Cypress cache folder and binary versions
            # to check if we are caching previous binary versions
            - run: npx cypress cache path
            - run: npx cypress cache list
            - run: npx cypress info
            # let's print version info
            - run: npx cypress version
            - run: npx cypress version --component package
            - run: npx cypress version --component binary
            - run: npx cypress version --component electron
            - run: npx cypress version --component node

      - release:
          filters:
            branches:
              only:
                - main
          requires:
            - 2 machines using Chrome
